#!/bin/bash
# vim: set ft=sh:

CHAIN_NAME=commission
CHAIN_FILE=/tmp/$HOSTNAME-$CHAIN_NAME-$(date +'%y-%m-%d@%H:%M:%S')

TREATMENT_DATE=""

for i in "$@"
do
    case $i in
    --treatment_date=*)
        TREATMENT_DATE="${i#*=}"
    shift
    ;;
    *)
    shift
    echo "'$i' ignored (unknown argument)" 1>&2
    ;;

esac
done

[ -z "$TREATMENT_DATE" ] && echo 'Missing treatment_date' && exit 1

chain_begin

chain_step commission.invoice_principal.create_empty --treatment_date="$TREATMENT_DATE"
chain_wait commission.invoice_principal.create_empty || chain_end
chain_step commission.invoice_principal.link --treatment_date="$TREATMENT_DATE"
chain_wait commission.invoice_principal.link || chain_end
chain_step commission.invoice_principal.finalize --treatment_date="$TREATMENT_DATE"
chain_wait commission.invoice_principal.finalize || chain_end

chain_end
