#!/bin/bash
# vim: set ft=sh:

CHAIN_NAME=commission

CHAIN_PARAMETERS=('TREATMENT_DATE' 'CONNECTION_DATE')
CHAIN_REQUIRED=('TREATMENT_DATE')

chain_params "$@"
chain_begin

chain_step commission.invoice_principal.create_empty ${GIVEN_PARAMETERS[@]}
chain_wait commission.invoice_principal.create_empty || chain_end
chain_step commission.invoice_principal.link ${GIVEN_PARAMETERS[@]}
chain_wait commission.invoice_principal.link || chain_end
chain_step commission.invoice_principal.finalize ${GIVEN_PARAMETERS[@]}
chain_wait commission.invoice_principal.finalize || chain_end

chain_end
