workspace:
  base: /workspace/drone
  path: coog

clone:
  git:
    image: plugins/git
    recursive: true
    skip_verify: true
    submodule_override:
      bin/vendor/tryton-perf-analyzer: https://github.com/coopengo/tryton-perf-analyzer.git

pipeline:
  check-meta: 
    image: coog-test/base-tests
    secrets: [ GITHUB_TOKEN, REDMINE_TOKEN ]
    commands:
      - node /workspace/drone/coog/drone/check-meta.js
    when:
      status: [ success, failure ]

  check-flake8:
    image: coog-test/base-tests
    group: checks
    commands:
      - /workspace/drone/coog/drone/check-flake8
    status: [ success, failure ]
    event: [pull_request]

  test-modules:
    image: coog-test/base-tests
    secrets: [ GITHUB_TOKEN ]
    environment:
      - PYTHONPATH=/workspace/drone/coog/bin/lib:/workspace/trytond:/workspace/proteus
      - DB_CACHE="/workspace/drone/coog-test-manual-db-cache"
      - TRYTOND_ASYNC_RQ="redis://127.0.0.1:6379/1"
    commands:
      - node /workspace/drone/coog/drone/check-meta.js tests || /workspace/drone/coog/drone/check-tests
    when:
      status: [ success, failure ]
      event: [pull_request]

services:
  database:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis
