workspace:
  base: /workspace/drone
  path: coog

clone:
  git:
    image: plugins/git
    recursive: true
    skip_verify: true
    submodule_override:
      bin/vendor/tryton-perf-analyzer: https://github.com/coopengo/tryton-perf-analyzer.git

pipeline:
  before-check:
    image: coog-test/base-tests
    commands:
      - git clone --recursive --depth=1 https://github.com/coopengo/coog-drone /workspace/drone/tests
      - /workspace/drone/tests/checks/before-check

  check-meta:
    image: coog-test/base-tests
    secrets: [ GITHUB_TOKEN, REDMINE_TOKEN ]
    commands:
      - /workspace/drone/tests/checks/check-meta.py
    when:
      status: [ success, failure ]

  check-flake8:
    image: coog-test/base-tests
    secrets: [ GITHUB_TOKEN ]
    commands:
      - /workspace/drone/tests/checks/check-flake8
    when:
      status: [ success, failure ]
      event: [pull_request]

  test-modules:
    image: coog-test/base-tests
    secrets: [ GITHUB_TOKEN ]
    environment:
      - PYTHONPATH=/workspace/drone/coog/bin/lib:/workspace/drone/trytond:/workspace/drone/proteus
      - DB_CACHE="/workspace/drone/coog-test-manual-db-cache"
      - TRYTOND_ASYNC_RQ="redis://127.0.0.1:6379/1"
    commands:
      - /workspace/drone/tests/checks/check-meta.py tests || /workspace/drone/tests/checks/check-tests
    when:
      status: [ success, failure ]
      event: [pull_request]

services:
  database:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis
