#!/bin/bash
# vim: set ft=sh:

CHAIN_NAME=commission
CHAIN_FILE=/tmp/$HOSTNAME-$CHAIN_NAME-$(date +'%y-%m-%d@%H:%M:%S')

TREATMENT_DATE=""
AGENT_TYPE=""
WITH_DRAFT=""

for i in "$@"
do
    case $i in
    --treatment_date=*)
        TREATMENT_DATE="${i#*=}"
    shift
    ;;
    --agent_type=*)
        AGENT_TYPE="${i#*=}"
    shift
    ;;
    --with_draft=*)
        WITH_DRAFT="${i#*=}"
    shift
    ;;
        *)
    shift
    echo "'$i' ignored (unknown argument)" 1>&2
    ;;
esac
done

[ -z "$TREATMENT_DATE" ] && echo 'Missing treatment_date' && exit 1
[ -z "$AGENT_TYPE" ] && echo 'Missing agent_type' && exit 1

chain_begin

chain_step commission.invoice.create --treatment_date="$TREATMENT_DATE" \
    --agent_type="$AGENT_TYPE"
chain_wait commission.invoice.create || chain_end

[[ -z  $WITH_DRAFT ]] && chain_step commission.invoice.post \
    --treatment_date="$TREATMENT_DATE" --agent_type="$AGENT_TYPE"
[[ ! -z  $WITH_DRAFT ]] && chain_step commission.invoice.post \
    --treatment_date="$TREATMENT_DATE" --agent_type="$AGENT_TYPE" \
    --with_draft="$WITH_DRAFT"
chain_wait commission.invoice.post || chain_end

chain_end
