#!/bin/bash
# vim: set ft=sh:

CHAIN_NAME=companies

CHAIN_PARAMETERS=('TREATMENT_DATE' 'CONNECTION_DATE' 'NONE-FIELDS' 'UPDATE')
CHAIN_REQUIRED=()

chain_params "$@"
chain_begin

chain_step migrator.country ${GIVEN_PARAMETERS[@]}
chain_wait migrator.country || chain_end

chain_step migrator.zip ${GIVEN_PARAMETERS[@]}
chain_wait migrator.zip || chain_end

chain_step migrator.address ${GIVEN_PARAMETERS[@]}
chain_wait migrator.address || chain_end

chain_end
