#!/bin/bash
# vim: set ft=sh:

CHAIN_NAME=companies

CHAIN_PARAMETERS=('TREATMENT_DATE' 'CONNECTION_DATE' 'NONE-FIELDS' 'UPDATE')
CHAIN_REQUIRED=()

chain_params "$@"
chain_begin

chain_step migrator.company ${GIVEN_PARAMETERS[@]} --none-fields='["parent_company"]'
chain_wait migrator.company || chain_end

chain_step migrator.company ${GIVEN_PARAMETERS[@]}
chain_wait migrator.company || chain_end

chain_end
