#!/bin/sh

get_modules() {
        (cd /workspace/drone/coog \
        && git diff --name-only $(git merge-base origin/"$DRONE_BRANCH" "$DRONE_COMMIT_SHA") "$DRONE_COMMIT_SHA" \
	| grep "^modules" \
	| cut -d "/" -f 2 \
	| sort | uniq )
}

main() {
	local errors;
	local modules; modules=$(get_modules)
	errors=$(flake8 --config=/workspace/drone/coog/tox.ini "$modules")

	if [ -z "$errors" ]
	then
		echo "No flake8 error detected, good job!"
	else
		echo "$errors" && return 1
	fi
}

main
