#!/bin/bash
# vim: set ft=sh:

CHAIN_NAME=companies

CHAIN_PARAMETERS=('TREATMENT_DATE' 'CONNECTION_DATE' 'NONE-FIELDS' 'UPDATE')
CHAIN_REQUIRED=()

chain_params "$@"
chain_begin

chain_step migrator.bank ${GIVEN_PARAMETERS[@]}
chain_wait migrator.bank || chain_end

chain_step migrator.bank_agency ${GIVEN_PARAMETERS[@]}
chain_wait migrator.bank_agency || chain_end

chain_step migrator.bank_account ${GIVEN_PARAMETERS[@]}
chain_wait migrator.bank_account || chain_end

chain_end
