#!/bin/bash
# vim: set ft=sh:

CHAIN_NAME=create_indemnifications
CHAIN_FILE=/tmp/$HOSTNAME-$CHAIN_NAME-$(date +'%y-%m-%d@%H:%M:%S')

CHAIN_PARAMETERS=('TREATMENT_DATE' 'CONNECTION_DATE')
CHAIN_REQUIRED=('TREATMENT_DATE')

chain_params "$@"
chain_begin

chain_step claim.indemnification.create ${GIVEN_PARAMETERS[@]}
chain_wait claim.indemnification.create || chain_end

chain_end
