#!/bin/bash
# vim: set ft=sh:

CHAIN_NAME=payment
CHAIN_FILE=/tmp/$HOSTNAME-$CHAIN_NAME-$(date +'%y-%m-%d@%H:%M:%S')

CHAIN_PARAMETERS=('TREATMENT_DATE' 'CONNECTION_DATE' 'PAYMENT_KIND' 'JOURNAL_METHODS' 'OUT')
CHAIN_REQUIRED=('TREATMENT_DATE' 'PAYMENT_KIND' 'JOURNAL_METHODS')

chain_params "$@"
chain_begin

chain_step account.payment.create --treatment_date="$TREATMENT_DATE" \
    --payment_kind="$PAYMENT_KIND"
chain_wait account.payment.create || chain_end

[[ -z  $OUT ]] && chain_step account.payment.process \
    --treatment_date="$TREATMENT_DATE" --payment_kind="$PAYMENT_KIND" \
    --journal_methods="$JOURNAL_METHODS"
chain_wait account.payment.process || chain_end
[[ ! -z  $OUT ]] && chain_step account.payment.process \
    --treatment_date="$TREATMENT_DATE" --payment_kind="$PAYMENT_KIND" \
    --journal_methods="$JOURNAL_METHODS" --out=$OUT
chain_wait account.payment.process || chain_end

chain_step account.payment.do_sepa_messages
chain_wait account.payment.do_sepa_messages || chain_end

chain_end
