#!/bin/bash
# vim: set ft=sh:

CHAIN_NAME=payment_fail
CHAIN_FILE=/tmp/$HOSTNAME-$CHAIN_NAME-$(date +'%y-%m-%d@%H:%M:%S')

TREATMENT_DATE=""
PARAMS=()

for i in "$@"
do
    case $i in
    --treatment_date=*)
        TREATMENT_DATE="${i#*=}"
        PARAMS+=($i)
    shift
    ;;
    --out=*)
        PARAMS+=($i)
    shift
    ;;
    --in=*)
        PARAMS+=($i)
    shift
    ;;
        *)
    shift
    echo "'$i' ignored (unknown argument)" 1>&2
    ;;
    esac
done

[ -z "$TREATMENT_DATE" ] && echo 'Missing treatment_date' && exit 1

chain_begin

chain_step account.payment.fail ${PARAMS[@]}
chain_wait account.payment.fail || chain_end

chain_end
