#!/bin/bash
# vim: set ft=sh:

CHAIN_NAME=payment_fail
CHAIN_FILE=/tmp/$HOSTNAME-$CHAIN_NAME-$(date +'%y-%m-%d@%H:%M:%S')

CHAIN_PARAMETERS=('IN_DIRECTORY' 'ARCHIVE')
CHAIN_REQUIRED=()

chain_params "$@"
chain_begin

chain_step account.payment.fail --in_directory="$IN_DIRECTORY"
chain_wait account.payment.fail || chain_end

chain_step account.payment.fail.message.create  --in_directory="$IN_DIRECTORY" --archive="$ARCHIVE"
chain_wait account.payment.fail.message.create || chain_end

chain_end
