#!/bin/bash
# vim: set ft=sh:

CHAIN_NAME=payment_fail

CHAIN_PARAMETERS=('IN_DIRECTORY' 'ARCHIVE')
CHAIN_REQUIRED=()

chain_params "$@"
chain_begin

if [ -z "$IN_DIRECTORY" ]; then
    chain_step account.payment.fail --in_directory="$IN_DIRECTORY"
else
    chain_step account.payment.fail
fi

chain_wait account.payment.fail || chain_end

chain_step account.payment.fail.message.create  --in_directory="$IN_DIRECTORY" --archive="$ARCHIVE"
chain_wait account.payment.fail.message.create || chain_end

chain_end
