#!/bin/bash

docker run -d --name test-postgres-commit -e POSTGRES_PASSWORD=postgres -p 5433:5432 postgres:9.5
docker run -d --name test-postgres-master -e POSTGRES_PASSWORD=postgres -p 5434:5432 postgres:9.5
docker run -d --name test-postgres-1-8 -e POSTGRES_PASSWORD=postgres -p 5435:5432 postgres:9.5
docker run -d --name test-postgres-1-10 -e POSTGRES_PASSWORD=postgres -p 5436:5432 postgres:9.5

docker run -d --name test-redis-commit -p 6380:6379 redis:3.2-alpine
docker run -d --name test-redis-master -p 6381:6379 redis:3.2-alpine
docker run -d --name test-redis-1-8 -p 6382:6379 redis:3.2-alpine
docker run -d --name test-redis-1-10 -p 6383:6379 redis:3.2-alpine
