#!/bin/bash

PATH="/usr/local/bin:$PATH"
export PATH

USER=test
export USER
HOME=/home/$USER
export HOME

. $HOME/.profile

COOG_TMP=/var/log/coog
export COOG_TMP

workon coog-commit
coog test commit master &>> $COOG_TMP/test-logs
deactivate

workon coog-master
TRYTOND_ASYNC_RQ=redis://localhost:6379/1 coog test fullcheck master &>> $COOG_TMP/test-logs
deactivate

workon coog-1.8
TRYTOND_ASYNC_RQ=redis://localhost:6379/3 coog test fullcheck coog-1.8 &>> $COOG_TMP/test-logs
deactivate
