#!/bin/bash

PATH="/usr/local/bin:$PATH"
export PATH

USER=test
export USER
HOME=/home/$USER
export HOME

. $HOME/.profile

workon coog-commit
COOG_TMP=/var/log/coog
export COOG_TMP
coog test commit &>> $COOG_TMP/test-logs
deactivate

workon coog-full
coog test fullcheck &>> $COOG_TMP/test-logs
deactivate
