#!/bin/bash

PATH="/usr/local/bin:$PATH"
export PATH

USER=test
export USER
HOME=/home/$USER
export HOME

. $HOME/.profile

COOG_TMP=/var/log/coog
export COOG_TMP

workon coog-master
coog test fullstart master 8 &>> $COOG_TMP/test-logs
deactivate
