#!/bin/bash

PATH="/usr/local/bin:$PATH"
export PATH

USER=test
export USER
HOME=/home/$USER
export HOME

. $HOME/.profile

COOG_TMP=/var/log/coog
export COOG_TMP

workon coog-master
TRYTOND_ASYNC_RQ=redis://localhost:6379/1 coog test fullstart master 4 &>> $COOG_TMP/test-logs
deactivate
