#!/bin/bash
# vim: set ft=sh:

CHAIN_NAME=document_process
CHAIN_FILE=/tmp/$HOSTNAME-$CHAIN_NAME-$(date +'%y-%m-%d@%H:%M:%S')

CHAIN_PARAMETERS=('TREATMENT_DATE' 'CONNECTION_DATE' 'ON_MODEL')
CHAIN_REQUIRED=('TREATMENT_DATE' 'ON_MODEL')

chain_params "$@"
chain_begin

chain_step document.request.process --treatment_date="$TREATMENT_DATE"
chain_wait document.request.process || chain_end
chain_step batch.remind.documents --treatment_date="$TREATMENT_DATE" \
    --on_model="$ON_MODEL"
chain_wait batch.remind.documents || chain_end

chain_end
