#!/bin/bash
# vim: set ft=sh:

CHAIN_NAME=document_process
CHAIN_FILE=/tmp/$HOSTNAME-$CHAIN_NAME-$(date +'%y-%m-%d@%H:%M:%S')

TREATMENT_DATE=""
ON_MODEL=""

for i in "$@"
do
    case $i in
    --treatment_date=*)
        TREATMENT_DATE="${i#*=}"
    shift
    ;;
    --on_model=*)
        ON_MODEL="${i#*=}"
    shift
    ;;
        *)
    shift
    echo "'$i' ignored (unknown argument)" 1>&2
    ;;
    esac
done

[ -z "$TREATMENT_DATE" ] && echo 'Missing treatment_date' && exit 1
[ -z "$ON_MODEL" ] && echo 'Missing on_model' && exit 1

chain_begin

chain_step document.request.process --treatment_date="$TREATMENT_DATE" \
chain_wait document.request.process || chain_end
chain_step batch.remind.documents --treatment_date="$TREATMENT_DATE" \
    --on_model="$ON_MODEL"
chain_wait batch.remind.documents || chain_end

chain_end
