#!/bin/bash
# vim: set ft=sh:

CHAIN_NAME=report_aged_balance

CHAIN_PARAMETERS=('TREATMENT_DATE' 'CONNECTION_DATE' 'TERM1' 'TERM2' 'TERM3' \
                    'TYPE' 'UNIT' 'POSTED' 'OUTPUT_DIR' 'POSSIBLE_DAYS' \
                    'WORKING_DAYS' 'CONF_CODE')
CHAIN_REQUIRED=('TREATMENT_DATE' 'WORKING_DAYS' 'CONF_CODE')

chain_params "$@"
chain_begin

chain_step account.aged_balance.generate ${GIVEN_PARAMETERS[@]}
chain_wait account.aged_balance.generate || chain_end

chain_end
