#!/bin/bash
# vim: set ft=sh:

CHAIN_NAME=noemie_929

CHAIN_PARAMETERS=('IN_DIRECTORY' 'OUT_DIRECTORY')
CHAIN_REQUIRED=('IN_DIRECTORY' 'OUT_DIRECTORY')

chain_params "$@"
chain_begin

chain_step contract.noemie.flow.batch ${GIVEN_PARAMETERS[@]}
chain_wait contract.noemie.flow.batch || chain_end

chain_end
