#!/bin/bash
# vim: set ft=sh:

CHAIN_NAME=check
CHAIN_FILE=/tmp/$HOSTNAME-$CHAIN_NAME-$(date +'%y-%m-%d@%H:%M:%S')

CHAIN_PARAMETERS=('CRASH')
CHAIN_REQUIRED=()

chain_params "$@"
chain_begin

if [ -z "$CRASH" ]
then
    chain_step ir.ui.view.validate --crash="$CRASH"
else
    chain_step ir.ui.view.validate
fi

chain_wait ir.ui.view.validate || chain_end

chain_end
