#!/bin/bash
# vim: set ft=sh:

CHAIN_NAME=check

CHAIN_PARAMETERS=('CRASH')
CHAIN_REQUIRED=()

chain_params "$@"
chain_begin

chain_step ir.ui.view.validate ${GIVEN_PARAMETERS[@]}

chain_wait ir.ui.view.validate || chain_end

chain_end
