#!/bin/bash
# vim: set ft=sh:

CHAIN_NAME=terminate_option

CHAIN_PARAMETERS=('TREATMENT_DATE' 'CONNECTION_DATE' 'WORKING_DAYS' 'CONF_CODE')
CHAIN_REQUIRED=('TREATMENT_DATE')

chain_params "$@"
chain_begin

chain_step contract.option.terminate ${GIVEN_PARAMETERS[@]}
chain_wait contract.option.terminate || chain_end

chain_end
