#!/bin/bash

clone_repo() { # <wd> <repo_uri> <repo_name>
        [ $# -ne 3 ] && echo bad args >&2 && return 1
        git clone --depth=1 --recursive "$2" "$1/workspace/$3"
        printf "%s:" "$3" >> "$1/workspace/.version"
        (cd "$1/workspace/$3" && git rev-parse HEAD >> "$1/workspace/.version")
}

main() { # <image-tag> [docker-build-arg*]
        [ $# -lt 1 ] && echo "Usage: ./build <image-tag> [docker-build-args]" >&2 && return 1

        local script_path; script_path=$(readlink -f "$0")
        local wd; wd=$(dirname "$script_path")
        local workspace="$wd/workspace"

        mkdir "$workspace" || return 1

        while read repository
        do
                local repo; repo=$(echo "$repository" | cut -d ";" -f 1)
                local uri; uri=$(echo "$repository" | cut -d ";" -f 2)
                echo "cloning $repo from $uri"
                clone_repo "$wd" "$uri" "$repo" || return 1
        done < "$wd/repositories"

        docker build -t "$@" "$wd"

        rm -rf "$workspace"
}

main "$@"
