#!/bin/bash

clone_repo() {  # <WD> <REPO_URI> <REPO_NAME>
	[ $# -ne 3 ] && echo bad args && return 1
	git clone --depth=1 --recursive $2 "$1/workspace/$3"
}

main() {    # build docker image [docker-build-arg*]
        [ $# -lt 1 ] && echo "Usage: ./build <IMAGE_NAME> [docker-build-args]" && \
                return 1

        local script_path; script_path=$(readLink -f "$0")

        local wd; wd=$(dirname "$script_path")
        local workspace="$wd/workspace"

        # Creating workspace directory
        mkdir "$workspace" 2> /dev/null

        local image; image=$1
        shift
	while read repository
        do
                local repo; repo=`echo $repository | cut -d ";" -f 1`
                local uri; uri=`echo $repository | cut -d ";" -f 2`

                if [ ! -d $wd/workspace/$repo ]
                then
                        echo "Working on $repo..."
			echo "Adress is $uri."
			clone_repo "$wd" "$uri" "$repo"
                else
                        echo "$repo detected."
                fi
        done < $wd/repositories

        docker build -t $image $* .

        echo "Removing temporary files." &&
        rm -rf "$workspace"
}

main $@
