#!/bin/bash
# vim: set ft=sh:

CHAIN_NAME=decline_inactive

CHAIN_PARAMETERS=('TREATMENT_DATE' 'CONNECTION_DATE' 'WORKING_DAYS' 'CONF_CODE')
CHAIN_REQUIRED=('TREATMENT_DATE' 'WORKING_DAYS' 'CONF_CODE')

chain_params "$@"
chain_begin

chain_step contract.decline.inactive_quotes ${GIVEN_PARAMETERS[@]}
chain_wait contract.decline.inactive_quotes || chain_end

chain_end
