#!/bin/bash
# vim: set ft=sh:

CHAIN_NAME=claim_stock
CHAIN_FILE=/tmp/$HOSTNAME-$CHAIN_NAME-$(date +'%y-%m-%d@%H:%M:%S')

CHAIN_PARAMETERS=('TREATMENT_DATE' 'CONNECTION_DATE' 'POSSIBLE_DAYS'    \
                    'PRODUCTS' 'WORKING_DAYS' 'CONF_CODE')
CHAIN_REQUIRED=('TREATMENT_DATE' 'WORKING_DAYS' 'CONF_CODE')

chain_params "$@"
chain_begin

chain_step insurer_reporting.claim.generate ${GIVEN_PARAMETERS[@]}
chain_wait insurer_reporting.claim.generate || chain_end

chain_end
