#!/bin/bash
# vim: set ft=sh:

CHAIN_NAME=bank_mobility

CHAIN_PARAMETERS=('IN_DIRECTORY' 'ARCHIVE')
CHAIN_REQUIRED=('IN_DIRECTORY' 'ARCHIVE')

chain_params "$@"
chain_begin

chain_step bank.mobility --in_directory="$IN_DIRECTORY" \
    --archive="$ARCHIVE"
chain_wait bank.mobility || chain_end

chain_end
