#!/bin/bash
# vim: set ft=sh:

CHAIN_NAME=extract_snapshot

CHAIN_PARAMETERS=('TREATMENT_DATE' 'CONNECTION_DATE' 'FLUSH_SIZE' 'OUTPUT_FILENAME' 'OUTPUT_DIR')
CHAIN_REQUIRED=('TREATMENT_DATE')

chain_params "$@"
chain_begin

chain_step account.move.aggregated.extract ${GIVEN_PARAMETERS[@]}
chain_wait account.move.aggregated.extract

chain_end
