#!/bin/bash
# vim: set ft=sh:

CHAIN_NAME=snapshot
CHAIN_FILE=/tmp/$HOSTNAME-$CHAIN_NAME-$(date +'%y-%m-%d@%H:%M:%S')

CHAIN_PARAMETERS=('CONNECTION_DATE')
CHAIN_REQUIRED=()

chain_params "$@"
chain_begin

chain_step account.move.snapshot.take ${GIVEN_PARAMETERS[@]}
chain_wait account.move.snapshot.take || chain_end

chain_end
