#!/bin/bash
# vim: set ft=sh:

CHAIN_NAME=process

CHAIN_PARAMETERS=('TREATMENT_DATE' 'CONNECTION_DATE')
CHAIN_REQUIRED=('TREATMENT_DATE')

chain_params "$@"
chain_begin

chain_step planned.event.process ${GIVEN_PARAMETERS[@]}
chain_wait planned.event.process || chain_end

chain_end
