#!/bin/bash
# vim: set ft=sh:

CHAIN_NAME=almerys

CHAIN_PARAMETERS=('TREATMENT_DATE')
CHAIN_REQUIRED=('TREATMENT_DATE')

chain_params "$@"
chain_begin

chain_step third_party_protocol.batch.almerys --treatment_date="$TREATMENT_DATE"
chain_wait third_party_protocol.batch.almerys || chain_end

chain_end
