#!/bin/bash
# vim: set ft=sh:

CHAIN_NAME=almerys_return

CHAIN_PARAMETERS=('IN_PATH' 'ARCHIVE_PATH')
CHAIN_REQUIRED=()

chain_params "$@"
chain_begin

chain_step batch.almerys.feedback --in_path="$IN_PATH" \
    --archive_path="$ARCHIVE_PATH"
chain_wait batch.almerys.feedback || chain_end

find $IN_PATH -name "*.xml" -exec mv -t $ARCHIVE_PATH {} +

chain_end
