#!/bin/bash
# vim: set ft=sh:

CHAIN_NAME=produce_request
CHAIN_FILE=/tmp/$HOSTNAME-$CHAIN_NAME-$(date +'%y-%m-%d@%H:%M:%S')

CHAIN_PARAMETERS=('CONNECTION_DATE')
CHAIN_REQUIRED=()

chain_params "$@"
chain_begin

chain_step report_production.request.batch_treat
chain_wait report_production.request.batch_treat || chain_end

chain_end
