#!/bin/sh
# This is for the 'update-rc.d', so it knows when to start your service.
### BEGIN INIT INFO
# Provides:          coog_server
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Manage coog server
# Description:       Manage coog server
### END INIT INFO
SCRIPT=`readlink -f $0`
SCRIPTPATH=`dirname $SCRIPT`
log () {
    echo "$@"
    logger -p user.info -t "Coopengo Server $SERVERNAME [$$]" "$@"
}
start()
{
     python $SCRIPTPATH/script_launcher.py start server 2>&1 | log &
}

stop()
{
     python $SCRIPTPATH/script_launcher.py kill server 2>&1 | log &
}

restart()
{
    stop;
    sleep 1;
    start;
}
case $1 in
start) 
      start;;
stop)
      stop;;
restart)
      restart;;
*)
      start;;
esac
