#!/bin/bash
# vim: set ft=sh:

CHAIN_NAME=invoice
CHAIN_FILE=/tmp/$HOSTNAME-$CHAIN_NAME-$(date +'%y-%m-%d@%H:%M:%S')

CHAIN_PARAMETERS=('TREATMENT_DATE' 'CONNECTION_DATE')
CHAIN_REQUIRED=('TREATMENT_DATE')

chain_params "$@"
chain_begin

chain_step contract.invoice.create ${GIVEN_PARAMETERS[@]}
chain_wait contract.invoice.create || chain_end

chain_step contract.invoice.set_number ${GIVEN_PARAMETERS[@]}
chain_wait contract.invoice.set_number || chain_end

chain_step contract.invoice.post ${GIVEN_PARAMETERS[@]}
chain_wait contract.invoice.post || chain_end

chain_end
