#!/bin/bash
# vim: set ft=sh:

CHAIN_NAME=renew
CHAIN_FILE=/tmp/$HOSTNAME-$CHAIN_NAME-$(date +'%y-%m-%d@%H:%M:%S')

CHAIN_PARAMETERS=('TREATMENT_DATE' 'CONNECTION_DATE')
CHAIN_REQUIRED=('TREATMENT_DATE')

chain_params "$@"
chain_begin

chain_step contract.renew --treatment_date="$TREATMENT_DATE"
chain_wait contract.renew || chain_end

chain_end
