#!/bin/bash
# vim: set ft=sh:

CHAIN_NAME=insurer_invoice

CHAIN_PARAMETERS=('TREATMENT_DATE' 'CONNECTION_DATE' 'NOTICE_KIND')
CHAIN_REQUIRED=('TREATMENT_DATE')

chain_params "$@"
chain_begin

chain_step account.insurer_invoice.create_empty ${GIVEN_PARAMETERS[@]}
chain_wait account.insurer_invoice.create_empty || chain_end
chain_step account.insurer_invoice.link ${GIVEN_PARAMETERS[@]}
chain_wait account.insurer_invoice.link || chain_end
chain_step account.insurer_invoice.finalize ${GIVEN_PARAMETERS[@]}
chain_wait account.insurer_invoice.finalize || chain_end

chain_end
