#!/bin/bash

source ./config

file_name ()
{
        echo $WORKERS_DIR"coogw-"$2"."$1
}

start_worker ()
{
        local PID_FILE=$(file_name pid $1)
        [ -e $PID_FILE ] && echo coogw-$1 is already running && return
        local PORT=$[JSON_PORT+$1]
        local CNF_FILE=$(file_name cnf $1)
        local LOG_FILE=$(file_name log $1)
        local OUT_FILE=$(file_name out $1)
        sed -e "s,JSON_PORT,$PORT,g" ./trytond.conf > $CNF_FILE
        sed -e "s,LOG_FILE,$OUT_FILE,g" ./logging.conf > $LOG_FILE
        trytond -c $CNF_FILE --logconf $LOG_FILE &>> /dev/null &
        local PID=$!
        disown
        echo $PID > $PID_FILE
        echo coogw-$1 started - listening on port $PORT - $PID
}

stop_worker ()
{
        local PID_FILE=$(file_name pid $1)
        [ ! -e $PID_FILE ] && echo coogw-$1 not running && return
        local CNF_FILE=$(file_name cnf $1)
        local LOG_FILE=$(file_name log $1)
        local PID=$(<$PID_FILE)
        kill -TERM $PID
        echo coogw-$1 stopped - $PID
        rm $PID_FILE $CNF_FILE $LOG_FILE
}

list_workers ()
{
        for PID_FILE in $(file_name pid "*")
        do
                local PID=$(<$PID_FILE)
                echo $PID_FILE is running - $PID
        done
}
